version: '3.8'

services: 
  postgres:
    image: postgres:14.5
    container_name: diagrams_db
    restart: always
    env_file:
      - ./.env.docker
    ports:
      - 5432:5432
  
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env.docker
    container_name: diagrams_app
    restart: on-failure:10
    depends_on:
      - postgres
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    command: bash -c "npm run migrations && npm run seeds && npm start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5000/healthcheck"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s